package norm

import (
	"database/sql"
	"errors"
	"fmt"
	"reflect"
	"strings"
)

// shiftName shift name like DevicePolicyMap to device_policy_map
func shiftName(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 5) // Pre-allocate with some buffer for underscores
	for i, c := range s {
		if c >= 'A' && c <= 'Z' {
			if i != 0 {
				b.WriteByte('_')
			}
			b.WriteByte(byte(c + 32))
		} else {
			b.WriteRune(c)
		}
	}
	return "`" + b.String() + "`"
}

func rawFieldNames(in any, tag string, pg bool) []string {
	v := reflect.ValueOf(in)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	out := make([]string, 0, v.NumField())

	typ := v.Type()
	for i := range v.NumField() {
		// gets us a StructField
		fi := typ.Field(i)
		tagv := fi.Tag.Get(tag)
		switch tagv {
		case "-":
			continue
		case "":
			if pg {
				out = append(out, fi.Name)
			} else {
				out = append(out, fmt.Sprintf("`%s`", fi.Name))
			}
		default:
			// get tag name with the tag option, e.g.:
			// `db:"id"`
			// `db:"id,type=char,length=16"`
			// `db:",type=char,length=16"`
			// `db:"-,type=char,length=16"`
			if strings.Contains(tagv, ",") {
				tagv = strings.TrimSpace(strings.Split(tagv, ",")[0])
			}
			if tagv == "-" {
				continue
			}
			if len(tagv) == 0 {
				tagv = fi.Name
			}
			if pg {
				out = append(out, tagv)
			} else {
				out = append(out, fmt.Sprintf("`%s`", tagv))
			}
		}
	}

	return out
}

// strSlice2Map convert string slice to map
func strSlice2Map(s []string) (res map[string]struct{}) {
	res = make(map[string]struct{})
	for _, e := range s {
		res[e] = struct{}{}
	}
	return res
}

// modelStruct2Map convert struct to map, tag is the tag name of struct
func modelStruct2Map(obj any, tag string) map[string]any {
	t := reflect.TypeOf(obj)
	v := reflect.ValueOf(obj)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
		v = v.Elem()
	}

	data := make(map[string]any, t.NumField())

	for i := 0; i < t.NumField(); i++ {
		tagVal := t.Field(i).Tag.Get(tag)
		// skip fields without tag or explicitly ignored
		if tagVal == "" || tagVal == "-" {
			continue
		}

		field := v.Field(i)
		value := field.Interface()

		// normalize common sql.Null* types without using reflect.TypeOf on each iteration
		switch nv := value.(type) {
		case sql.NullByte:
			if nv.Valid {
				value = nv.Byte
			} else {
				value = nil
			}
		case sql.NullBool:
			if nv.Valid {
				value = nv.Bool
			} else {
				value = nil
			}
		case sql.NullFloat64:
			if nv.Valid {
				value = nv.Float64
			} else {
				value = nil
			}
		case sql.NullInt16:
			if nv.Valid {
				value = nv.Int16
			} else {
				value = nil
			}
		case sql.NullInt32:
			if nv.Valid {
				value = nv.Int32
			} else {
				value = nil
			}
		case sql.NullInt64:
			if nv.Valid {
				value = nv.Int64
			} else {
				value = nil
			}
		case sql.NullString:
			if nv.Valid {
				value = nv.String
			} else {
				value = nil
			}
		case sql.NullTime:
			if nv.Valid {
				value = nv.Time
			} else {
				value = nil
			}
		}

		data[tagVal] = value
	}
	return data
}

// modelStructSlice2MapSlice convert struct slice to map slice, tag is the tag name of struct
func modelStructSlice2MapSlice(obj any, tag string) []map[string]any {
	t := reflect.TypeOf(obj)
	v := reflect.ValueOf(obj)
	if t.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	data := make([]map[string]any, 0, v.Len())
	for i := 0; i < v.Len(); i++ {
		data = append(data, modelStruct2Map(v.Index(i).Interface(), tag))
	}
	return data
}

func createModelPointerAndSlice(input any) (any, any) {
	if input == nil {
		panic(errors.New("model is nil"))
	}

	inputType := reflect.ValueOf(input).Type()

	// we only accept structs
	if inputType.Kind() != reflect.Struct {
		panic(fmt.Errorf("model only can be a struct; got %s", inputType.Kind()))
	}

	inputPointer := reflect.New(inputType).Interface()

	slicePointer := reflect.New(reflect.SliceOf(inputType)).Interface()

	return inputPointer, slicePointer
}

// deepCopyModelPtrStructure deep copy a pointer struct model or a pointer slice model.
//
// The input must be a pointer to a struct or a pointer to a slice of structs, if not, return nil.
// I didn't check src type whether it is struct because it should be generated by the createModelPointerAndSlice function.
// So if this function return nil, check createModelPointerAndSlice first, make sure it can pass its unit test.
func deepCopyModelPtrStructure(src any) any {
	srcValue := reflect.ValueOf(src)

	if srcValue.Kind() != reflect.Ptr {
		return src
	}

	// create a new value of the same type as src
	return reflect.New(srcValue.Elem().Type()).Interface()
}

func getTableName(m any) string {
	if call, ok := reflect.TypeOf(m).MethodByName("TableName"); ok {
		return "`" + call.Func.Call([]reflect.Value{reflect.ValueOf(m)})[0].String() + "`"
	}

	return shiftName(reflect.TypeOf(m).Name())
}

func parseSelectColumns(selectSQL string) []string {
	if selectSQL == "" || selectSQL == Asterisk {
		return nil
	}
	parts := splitSelectClause(selectSQL)
	cols := make([]string, 0, len(parts))
	for _, p := range parts {
		col := strings.TrimSpace(p)
		if col == "" {
			continue
		}

		// Handle aliases like:
		// `id` AS user_id
		// `id` user_id
		lower := strings.ToLower(col)
		if idx := strings.LastIndex(lower, " as "); idx >= 0 {
			col = strings.TrimSpace(col[idx+4:])
		} else {
			items := strings.Fields(col)
			if len(items) > 1 {
				col = items[len(items)-1]
			}
		}

		// Handle qualified columns like `table`.`id` or table.id.
		if idx := strings.LastIndex(col, "."); idx >= 0 {
			col = strings.TrimSpace(col[idx+1:])
		}

		col = strings.Trim(col, "`")
		if col != "" {
			cols = append(cols, col)
		}
	}
	return cols
}

// splitSelectClause splits a select list by commas while ignoring commas inside parentheses.
func splitSelectClause(selectSQL string) []string {
	parts := make([]string, 0, 4)
	depth := 0
	start := 0

	for i, r := range selectSQL {
		switch r {
		case '(':
			depth++
		case ')':
			if depth > 0 {
				depth--
			}
		case ',':
			if depth == 0 {
				parts = append(parts, selectSQL[start:i])
				start = i + 1
			}
		}
	}

	parts = append(parts, selectSQL[start:])
	return parts
}

func hasSelectAlias(selectSQL string) bool {
	if selectSQL == "" || selectSQL == Asterisk {
		return false
	}

	for _, part := range splitSelectClause(selectSQL) {
		col := strings.TrimSpace(part)
		if col == "" {
			continue
		}

		if hasTopLevelAS(col) {
			return true
		}

		items := splitTopLevelFields(col)
		if len(items) < 2 {
			continue
		}

		prev := strings.ToLower(items[len(items)-2])
		if prev == "distinct" || prev == "all" {
			continue
		}

		if isLikelyAliasToken(items[len(items)-1]) {
			return true
		}
	}

	return false
}

func hasQualifiedWildcardSelect(selectSQL string) bool {
	if selectSQL == "" || selectSQL == Asterisk {
		return false
	}

	for _, part := range splitSelectClause(selectSQL) {
		col := strings.TrimSpace(part)
		if col == "" {
			continue
		}
		fields := splitTopLevelFields(col)
		if len(fields) == 0 {
			continue
		}
		if isQualifiedWildcardToken(fields[0]) {
			return true
		}
	}

	return false
}

func isQualifiedWildcardToken(token string) bool {
	token = strings.TrimSpace(token)
	token = strings.ReplaceAll(token, " ", "")
	if token == "" || token == Asterisk {
		return false
	}
	if !strings.HasSuffix(token, ".*") {
		return false
	}

	prefix := token[:len(token)-2]
	if prefix == "" {
		return false
	}

	segments := strings.Split(prefix, ".")
	for _, seg := range segments {
		if seg == "" {
			return false
		}
		if strings.HasPrefix(seg, "`") && strings.HasSuffix(seg, "`") && len(seg) >= 2 {
			inner := seg[1 : len(seg)-1]
			if inner == "" {
				return false
			}
			continue
		}
		if !isSimpleIdentifier(seg) {
			return false
		}
	}

	return true
}

func hasTopLevelAS(s string) bool {
	depth := 0
	inSingle := false
	inDouble := false
	inBacktick := false
	token := strings.Builder{}

	flushToken := func() bool {
		if token.Len() == 0 {
			return false
		}
		word := strings.ToLower(token.String())
		token.Reset()
		return word == "as"
	}

	for _, r := range s {
		switch {
		case inBacktick:
			if r == '`' {
				inBacktick = false
			}
			continue
		case inSingle:
			if r == '\'' {
				inSingle = false
			}
			continue
		case inDouble:
			if r == '"' {
				inDouble = false
			}
			continue
		}

		switch r {
		case '`':
			inBacktick = true
			if depth == 0 && flushToken() {
				return true
			}
		case '\'':
			inSingle = true
			if depth == 0 && flushToken() {
				return true
			}
		case '"':
			inDouble = true
			if depth == 0 && flushToken() {
				return true
			}
		case '(':
			if depth == 0 && flushToken() {
				return true
			}
			depth++
		case ')':
			if depth > 0 {
				depth--
			}
			if depth == 0 && flushToken() {
				return true
			}
		default:
			if depth > 0 {
				continue
			}
			if isWordChar(r) {
				token.WriteRune(r)
			} else if flushToken() {
				return true
			}
		}
	}

	return flushToken()
}

func splitTopLevelFields(s string) []string {
	depth := 0
	inSingle := false
	inDouble := false
	inBacktick := false
	fields := make([]string, 0, 2)
	start := -1

	flush := func(end int) {
		if start < 0 {
			return
		}
		fields = append(fields, s[start:end])
		start = -1
	}

	for i, r := range s {
		switch {
		case inBacktick:
			if r == '`' {
				inBacktick = false
			}
			continue
		case inSingle:
			if r == '\'' {
				inSingle = false
			}
			continue
		case inDouble:
			if r == '"' {
				inDouble = false
			}
			continue
		}

		switch r {
		case '`':
			inBacktick = true
			if start < 0 {
				start = i
			}
		case '\'':
			inSingle = true
			if start < 0 {
				start = i
			}
		case '"':
			inDouble = true
			if start < 0 {
				start = i
			}
		case '(':
			depth++
			if start < 0 {
				start = i
			}
		case ')':
			if depth > 0 {
				depth--
			}
			if start < 0 {
				start = i
			}
		default:
			if depth == 0 && isSpace(r) {
				flush(i)
				continue
			}
			if start < 0 {
				start = i
			}
		}
	}

	flush(len(s))
	return fields
}

func isLikelyAliasToken(token string) bool {
	token = strings.TrimSpace(token)
	if token == "" {
		return false
	}

	if strings.HasPrefix(token, "`") && strings.HasSuffix(token, "`") && len(token) >= 2 {
		return true
	}

	return isSimpleIdentifier(token)
}

func isWordChar(r rune) bool {
	return (r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_'
}

func isSpace(r rune) bool {
	return r == ' ' || r == '\t' || r == '\n' || r == '\r'
}

func isSimpleIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		if i == 0 {
			if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || r == '_') {
				return false
			}
			continue
		}
		if !((r >= 'a' && r <= 'z') || (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '_') {
			return false
		}
	}
	return true
}

func filterBySelectColumns(result map[string]any, selectSQL string) map[string]any {
	fields := parseSelectColumns(selectSQL)
	if len(fields) == 0 {
		return result
	}

	allowed := make(map[string]struct{}, len(fields))
	for _, f := range fields {
		allowed[f] = struct{}{}
	}

	filtered := make(map[string]any, len(allowed))
	for k, v := range result {
		if _, ok := allowed[k]; ok {
			filtered[k] = v
		}
	}
	return filtered
}
