package norm

import (
	"database/sql"
	"errors"
	"fmt"
	"reflect"
	"strings"
)

// shiftName shift name like DevicePolicyMap to device_policy_map
func shiftName(s string) string {
	var b strings.Builder
	b.Grow(len(s) + 5) // Pre-allocate with some buffer for underscores
	for i, c := range s {
		if c >= 'A' && c <= 'Z' {
			if i != 0 {
				b.WriteByte('_')
			}
			b.WriteByte(byte(c + 32))
		} else {
			b.WriteRune(c)
		}
	}
	return "`" + b.String() + "`"
}

func rawFieldNames(in any, tag string, pg bool) []string {
	v := reflect.ValueOf(in)
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	out := make([]string, 0, v.NumField())

	typ := v.Type()
	for i := range v.NumField() {
		// gets us a StructField
		fi := typ.Field(i)
		tagv := fi.Tag.Get(tag)
		switch tagv {
		case "-":
			continue
		case "":
			if pg {
				out = append(out, fi.Name)
			} else {
				out = append(out, fmt.Sprintf("`%s`", fi.Name))
			}
		default:
			// get tag name with the tag option, e.g.:
			// `db:"id"`
			// `db:"id,type=char,length=16"`
			// `db:",type=char,length=16"`
			// `db:"-,type=char,length=16"`
			if strings.Contains(tagv, ",") {
				tagv = strings.TrimSpace(strings.Split(tagv, ",")[0])
			}
			if tagv == "-" {
				continue
			}
			if len(tagv) == 0 {
				tagv = fi.Name
			}
			if pg {
				out = append(out, tagv)
			} else {
				out = append(out, fmt.Sprintf("`%s`", tagv))
			}
		}
	}

	return out
}

// strSlice2Map convert string slice to map
func strSlice2Map(s []string) (res map[string]struct{}) {
	res = make(map[string]struct{})
	for _, e := range s {
		res[e] = struct{}{}
	}
	return res
}

// modelStruct2Map convert struct to map, tag is the tag name of struct
func modelStruct2Map(obj any, tag string) map[string]any {
	t := reflect.TypeOf(obj)
	v := reflect.ValueOf(obj)
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
		v = v.Elem()
	}

	data := make(map[string]any, t.NumField())

	for i := 0; i < t.NumField(); i++ {
		tagVal := t.Field(i).Tag.Get(tag)
		// skip fields without tag or explicitly ignored
		if tagVal == "" || tagVal == "-" {
			continue
		}

		field := v.Field(i)
		value := field.Interface()

		// normalize common sql.Null* types without using reflect.TypeOf on each iteration
		switch nv := value.(type) {
		case sql.NullByte:
			if nv.Valid {
				value = nv.Byte
			} else {
				value = nil
			}
		case sql.NullBool:
			if nv.Valid {
				value = nv.Bool
			} else {
				value = nil
			}
		case sql.NullFloat64:
			if nv.Valid {
				value = nv.Float64
			} else {
				value = nil
			}
		case sql.NullInt16:
			if nv.Valid {
				value = nv.Int16
			} else {
				value = nil
			}
		case sql.NullInt32:
			if nv.Valid {
				value = nv.Int32
			} else {
				value = nil
			}
		case sql.NullInt64:
			if nv.Valid {
				value = nv.Int64
			} else {
				value = nil
			}
		case sql.NullString:
			if nv.Valid {
				value = nv.String
			} else {
				value = nil
			}
		case sql.NullTime:
			if nv.Valid {
				value = nv.Time
			} else {
				value = nil
			}
		}

		data[tagVal] = value
	}
	return data
}

// modelStructSlice2MapSlice convert struct slice to map slice, tag is the tag name of struct
func modelStructSlice2MapSlice(obj any, tag string) []map[string]any {
	t := reflect.TypeOf(obj)
	v := reflect.ValueOf(obj)
	if t.Kind() == reflect.Ptr {
		v = v.Elem()
	}

	data := make([]map[string]any, 0, v.Len())
	for i := 0; i < v.Len(); i++ {
		data = append(data, modelStruct2Map(v.Index(i).Interface(), tag))
	}
	return data
}

func createModelPointerAndSlice(input any) (any, any) {
	if input == nil {
		panic(errors.New("model is nil"))
	}

	inputType := reflect.ValueOf(input).Type()

	// we only accept structs
	if inputType.Kind() != reflect.Struct {
		panic(fmt.Errorf("model only can be a struct; got %s", inputType.Kind()))
	}

	inputPointer := reflect.New(inputType).Interface()

	slicePointer := reflect.New(reflect.SliceOf(inputType)).Interface()

	return inputPointer, slicePointer
}

// deepCopyModelPtrStructure deep copy a pointer struct model or a pointer slice model.
//
// The input must be a pointer to a struct or a pointer to a slice of structs, if not, return nil.
// I didn't check src type whether it is struct because it should be generated by the createModelPointerAndSlice function.
// So if this function return nil, check createModelPointerAndSlice first, make sure it can pass its unit test.
func deepCopyModelPtrStructure(src any) any {
	srcValue := reflect.ValueOf(src)

	if srcValue.Kind() != reflect.Ptr {
		return src
	}

	// create a new value of the same type as src
	return reflect.New(srcValue.Elem().Type()).Interface()
}

func getTableName(m any) string {
	if call, ok := reflect.TypeOf(m).MethodByName("TableName"); ok {
		return "`" + call.Func.Call([]reflect.Value{reflect.ValueOf(m)})[0].String() + "`"
	}

	return shiftName(reflect.TypeOf(m).Name())
}
