# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:

  Test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
          image: mysql:5.7
          ports:
            - 6033:3306
          options: >-
            --health-cmd="mysqladmin ping --silent"
            --health-interval=10s
            --health-timeout=5s
            --health-retries=3
          env:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: 123456
          
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
        
    - name: Install dependencies
      run: go mod tidy

    - name: Init test database
      run: mysql -h127.0.0.1 -P6033 -uroot -p123456 --silent <./test/ddl.sql
        
    - name: Test
      run: go test - v .
